Hello `3.x` development branch
reactphp/http pull request #527
Opened 2024-05-16 10:12 UTC by WyriHaximus

Once this PR is merged, we can start working on the new [v3.0.0 milestone](https://github.com/reactphp/http/milestone/37). The default branch will be `3.x` and the old `1.x` branch still stay in place at least until `3.0.0` is released.

Refs:
Road map ticket for http: #517
Plans for ReactPHP v3: https://github.com/orgs/reactphp/discussions/481 
PR templated from: https://github.com/friends-of-reactphp/mysql/pull/185

2024-05-16 12:06 UTC, SimonFrings requested changes
Small oversight for the link to the `1.x` branch

2024-05-16 12:06 UTC, SimonFrings commented on README.md
> +> [`1.x` branch](https://github.com/reactphp/socket/tree/1.x).
```suggestion
> [`1.x` branch](https://github.com/reactphp/http/tree/1.x).
```

2024-05-16 15:38 UTC, WyriHaximus commented on README.md
> +> [`1.x` branch](https://github.com/reactphp/socket/tree/1.x).
Fixed :+1:

2024-05-16 17:33 UTC, clue approved these changes

2024-05-17 06:29 UTC, SimonFrings approved these changes
Nice, let's get this in :+1:

2024-05-17 06:29 UTC, merged